title:
  en: Web Being
  fr: Web Being
  ru: МИРКА
tagline:
  en: Free-price web-studio
  fr: Free-price web-studio
  ru: Веб-волонтерство
index:
  en: index.html
  fr: accueil.html
  ru: privet.html
email: web-being@gmail.com
description:
  en: Startup initiative that promotes Pay What You Want website development. Because there are people who need website but don’t have money or knowledge how to do that
  fr: Oh lah lah
  ru:
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://web-being.com"
twitter_username: web-being
github_username:  web-being
permalink: :title

markdown: kramdown

kramdown:
  parse_block_html: true

defaults:
    - {scope: {path: ""}, values: {layout: "post"}}

prose:
  rooturl: ''
  siteurl: 'http://web-being.com'
  media: 'img'
  ignore: ['CNAME', '_config.yml', '*.json', '.gitignore', 'readme.md', '*.xml', 'admin.html']
  metadata:
    _posts:
      - name: "lang"
        field:
          element: "text"
          label: "Language"
          help: "en, fr or ru"
          value: "en"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          type: "text"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "The image will be used as a background cover for the post. Can be absolute or relative URL."
          placeholder: "img/cover.jpg"
          type: "url"
      - name: "comments"
        field:
          element: "checkbox"
          label: "Enable comments"
          help: "This will enable comments for the post"
          value: false
      - name: "when"
        field:
          element: "text"
          label: "When"
          help: "The date of the event"
          placeholder: "YYYY-MM-DD HH:MM"
          type: "datetime"
          value: ""
      - name: "where"
        field:
          element: "text"
          label: "Where"
          help: "The place of the event"
          placeholder: "Anticafé Montréal, 294, rue Sainte-Catherine Ouest, H2X 2A1, Montréal QC"
          type: "text"
          value: ""

t:
  en:
    home: "Home"
    about: "About"
    events: "Events"
    programs: "Programs"
  fr:
    home: "Accueil"
    about: "À propos"
    events: "Affiche"
    programs: "Programmes"
  zh:
    home: "首页"
    about: "关于"
  ru:
    home: "Главная"
    about: "О нас"
    events: "События"
    programs: "Программы"
